name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-django django djangorestframework requests
    - name: Analysing all project files with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing only changed files in commits with pylint
      run: |
        # Получаем список изменённых .py файлов в последнем коммите
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.py$')
        if [ -n "$CHANGED_FILES" ]; then
          pylint $CHANGED_FILES
        else
          echo "No Python files changed in this commit."
        fi
