name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-django django djangorestframework requests
    - name: Analysing changed files with pylint
      run: |
        # Если это первый push, проверяем все .py файлы в текущем состоянии
        if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
          CHANGED_FILES=$(git ls-files '*.py')
          echo "First push detected, checking all Python files in this commit."
        else
          # Иначе проверяем изменённые файлы между before и sha
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
          echo "Checking changed files in this push."
        fi
        
        # Если есть файлы для проверки, запускаем pylint
        if [ -n "$CHANGED_FILES" ]; then
          pylint $CHANGED_FILES
        else
          echo "No Python files changed in this push."
        fi
